export const dscrData: any[] = [
    {
        id: 1,
        retailer: 'Evangeline Peck',
        product_sku_sold: 'Bear Brand',
        price: 15,
        qty: 200,
        total_sales_amount: 15 * 200,
        payment_amount: 15 * 200,
        cash_sales: 3000,
        credit_sales: 0
    },
    {
        id: 2,
        retailer: 'Wesley Sellers',
        product_sku_sold: 'Bear Brand',
        price: 15,
        qty: 120,
        total_sales_amount: 15 * 120,
        payment_amount: 15 * 120,
        cash_sales: 1400,
        credit_sales: 1600
    },
    {
        id: 1,
        retailer: 'Evangeline Peck',
        product_sku_sold: 'Bear Brand',
        price: 15,
        qty: 200,
        total_sales_amount: 15 * 200,
        payment_amount: 15 * 200,
        cash_sales: 0,
        credit_sales: 3000
    },
    {
        id: 1,
        retailer: 'Konner Booker',
        product_sku_sold: 'Milo',
        price: 10,
        qty: 250,
        total_sales_amount: 10 * 250,
        payment_amount: 10 * 250,
        cash_sales: 1500,
        credit_sales: 1000
    },
    {
        id: 1,
        retailer: 'Abigayle Hall',
        product_sku_sold: 'Coffee',
        price: 20,
        qty: 100,
        total_sales_amount: 20 * 100,
        payment_amount: 20 * 100,
        cash_sales: 1000,
        credit_sales: 1000
    },
    {
        id: 1,
        retailer: 'Evangeline Peck',
        product_sku_sold: 'Bear Brand',
        price: 15,
        qty: 200,
        total_sales_amount: 15 * 200,
        payment_amount: 15 * 200,
        cash_sales: 2500,
        credit_sales: 0
    },
    {
        id: 1,
        retailer: 'Howard Singh',
        product_sku_sold: 'Tropicana',
        price: 35,
        qty: 40,
        total_sales_amount: 35 * 40,
        payment_amount: 35 * 40,
        cash_sales: 1400,
        credit_sales: 0
    },
    {
        id: 1,
        retailer: 'Carlie Krause',
        product_sku_sold: 'Smart C+',
        price: 35,
        qty: 100,
        total_sales_amount: 35 * 100,
        payment_amount: 35 * 100,
        cash_sales: 3500,
        credit_sales: 0
    },
    {
        id: 1,
        retailer: 'Evangeline Peck',
        product_sku_sold: 'Bear Brand',
        price: 15,
        qty: 200,
        total_sales_amount: 15 * 200,
        payment_amount: 15 * 200,
        cash_sales: 2500,
        credit_sales: 0
    },
    {
        id: 2,
        retailer: 'Wesley Sellers',
        product_sku_sold: 'Bear Brand',
        price: 15,
        qty: 120,
        total_sales_amount: 15 * 120,
        payment_amount: 15 * 120,
        cash_sales: 1200,
        credit_sales: 600
    },
    {
        id: 1,
        retailer: 'Evangeline Peck',
        product_sku_sold: 'Bear Brand',
        price: 15,
        qty: 200,
        total_sales_amount: 15 * 200,
        payment_amount: 15 * 200,
        cash_sales: 2400,
        credit_sales: 100
    },
    {
        id: 1,
        retailer: 'Konner Booker',
        product_sku_sold: 'Milo',
        price: 10,
        qty: 250,
        total_sales_amount: 10 * 250,
        payment_amount: 10 * 250,
        cash_sales: 2500,
        credit_sales: 0
    },
    {
        id: 1,
        retailer: 'Abigayle Hall',
        product_sku_sold: 'Coffee',
        price: 20,
        qty: 100,
        total_sales_amount: 20 * 100,
        payment_amount: 20 * 100,
        cash_sales: 2000,
        credit_sales: 0
    },
    {
        id: 1,
        retailer: 'Evangeline Peck',
        product_sku_sold: 'Bear Brand',
        price: 15,
        qty: 200,
        total_sales_amount: 15 * 200,
        payment_amount: 15 * 200,
        cash_sales: 3000,
        credit_sales: 0
    },
    {
        id: 1,
        retailer: 'Evangeline Peck',
        product_sku_sold: 'Bear Brand',
        price: 15,
        qty: 200,
        total_sales_amount: 15 * 200,
        payment_amount: 15 * 200,
        cash_sales: 3000,
        credit_sales: 0
    },
    {
        id: 2,
        retailer: 'Wesley Sellers',
        product_sku_sold: 'Bear Brand',
        price: 15,
        qty: 120,
        total_sales_amount: 15 * 120,
        payment_amount: 15 * 120,
        cash_sales: 1400,
        credit_sales: 1600
    },
    {
        id: 1,
        retailer: 'Evangeline Peck',
        product_sku_sold: 'Bear Brand',
        price: 15,
        qty: 200,
        total_sales_amount: 15 * 200,
        payment_amount: 15 * 200,
        cash_sales: 0,
        credit_sales: 3000
    },
    {
        id: 1,
        retailer: 'Konner Booker',
        product_sku_sold: 'Milo',
        price: 10,
        qty: 250,
        total_sales_amount: 10 * 250,
        payment_amount: 10 * 250,
        cash_sales: 1500,
        credit_sales: 1000
    },
    {
        id: 1,
        retailer: 'Abigayle Hall',
        product_sku_sold: 'Coffee',
        price: 20,
        qty: 100,
        total_sales_amount: 20 * 100,
        payment_amount: 20 * 100,
        cash_sales: 1000,
        credit_sales: 1000
    },
    {
        id: 1,
        retailer: 'Evangeline Peck',
        product_sku_sold: 'Bear Brand',
        price: 15,
        qty: 200,
        total_sales_amount: 15 * 200,
        payment_amount: 15 * 200,
        cash_sales: 2500,
        credit_sales: 0
    },
    {
        id: 1,
        retailer: 'Howard Singh',
        product_sku_sold: 'Tropicana',
        price: 35,
        qty: 40,
        total_sales_amount: 35 * 40,
        payment_amount: 35 * 40,
        cash_sales: 1400,
        credit_sales: 0
    },
    {
        id: 1,
        retailer: 'Carlie Krause',
        product_sku_sold: 'Smart C+',
        price: 35,
        qty: 100,
        total_sales_amount: 35 * 100,
        payment_amount: 35 * 100,
        cash_sales: 3500,
        credit_sales: 0
    },
    {
        id: 1,
        retailer: 'Evangeline Peck',
        product_sku_sold: 'Bear Brand',
        price: 15,
        qty: 200,
        total_sales_amount: 15 * 200,
        payment_amount: 15 * 200,
        cash_sales: 2500,
        credit_sales: 0
    },
    {
        id: 2,
        retailer: 'Wesley Sellers',
        product_sku_sold: 'Bear Brand',
        price: 15,
        qty: 120,
        total_sales_amount: 15 * 120,
        payment_amount: 15 * 120,
        cash_sales: 1200,
        credit_sales: 600
    },
    {
        id: 1,
        retailer: 'Evangeline Peck',
        product_sku_sold: 'Bear Brand',
        price: 15,
        qty: 200,
        total_sales_amount: 15 * 200,
        payment_amount: 15 * 200,
        cash_sales: 2400,
        credit_sales: 100
    },
    {
        id: 1,
        retailer: 'Konner Booker',
        product_sku_sold: 'Milo',
        price: 10,
        qty: 250,
        total_sales_amount: 10 * 250,
        payment_amount: 10 * 250,
        cash_sales: 2500,
        credit_sales: 0
    },
    {
        id: 1,
        retailer: 'Abigayle Hall',
        product_sku_sold: 'Coffee',
        price: 20,
        qty: 100,
        total_sales_amount: 20 * 100,
        payment_amount: 20 * 100,
        cash_sales: 2000,
        credit_sales: 0
    },
    {
        id: 1,
        retailer: 'Evangeline Peck',
        product_sku_sold: 'Bear Brand',
        price: 15,
        qty: 200,
        total_sales_amount: 15 * 200,
        payment_amount: 15 * 200,
        cash_sales: 3000,
        credit_sales: 0
    }
]