import { Inventory } from "./inventory.model";

export const testInventoryList: Inventory[] = [
    {
        id: 1,
        code: 'BRB101',
        name: 'Bear Brand Swak Pack',
        sku: 1000001,
        category: 'category 1',
        sub_category: 'sub category 2',
        price: 15,
        uom: 'gram',
        qty: 20,
        date_added: '2018-07-30',
    },
    {
        id: 2,
        code: 'BRB102',
        name: 'Bear Brand Adult Plus',
        sku: 1000002,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 15,
        uom: 'gram',
        qty: 25,
        date_added: '2018-07-29',
    },
    {
        id: 3,
        code: 'MILO101',
        name: 'Milo',
        sku: 1000009,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 8,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 4,
        code: 'PRM301',
        name: 'PREMIER 3in1',
        sku: 1006009,
        category: 'category 2',
        sub_category: 'sub category 1',
        price: 16,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 5,
        code: 'PRME321',
        name: 'PREMIER 3in1 ECO ',
        sku: 1007000,
        category: 'category 2',
        sub_category: 'sub category 3',
        price: 15,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-29',
    },
    {
        id: 6,
        code: 'PRM21',
        name: 'PREMIER 2 1 Pkt',
        sku: 2007000,
        category: 'category 3',
        sub_category: 'sub category 1',
        price: 20,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-28',
    },
    {
        id: 1,
        code: 'BRB101',
        name: 'Bear Brand Swak Pack',
        sku: 1000001,
        category: 'category 1',
        sub_category: 'sub category 2',
        price: 15,
        uom: 'gram',
        qty: 20,
        date_added: '2018-07-30',
    },
    {
        id: 2,
        code: 'BRB102',
        name: 'Bear Brand Adult Plus',
        sku: 1000002,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 15,
        uom: 'gram',
        qty: 25,
        date_added: '2018-07-29',
    },
    {
        id: 3,
        code: 'MILO101',
        name: 'Milo',
        sku: 1000009,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 8,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 4,
        code: 'PRM301',
        name: 'PREMIER 3in1',
        sku: 1006009,
        category: 'category 2',
        sub_category: 'sub category 1',
        price: 16,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 5,
        code: 'PRME321',
        name: 'PREMIER 3in1 ECO ',
        sku: 1007000,
        category: 'category 2',
        sub_category: 'sub category 3',
        price: 15,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-29',
    },
    {
        id: 6,
        code: 'PRM21',
        name: 'PREMIER 2 1 Pkt',
        sku: 2007000,
        category: 'category 3',
        sub_category: 'sub category 1',
        price: 20,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-28',
    },
    {
        id: 1,
        code: 'BRB101',
        name: 'Bear Brand Swak Pack',
        sku: 1000001,
        category: 'category 1',
        sub_category: 'sub category 2',
        price: 15,
        uom: 'gram',
        qty: 20,
        date_added: '2018-07-30',
    },
    {
        id: 2,
        code: 'BRB102',
        name: 'Bear Brand Adult Plus',
        sku: 1000002,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 15,
        uom: 'gram',
        qty: 25,
        date_added: '2018-07-29',
    },
    {
        id: 3,
        code: 'MILO101',
        name: 'Milo',
        sku: 1000009,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 8,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 4,
        code: 'PRM301',
        name: 'PREMIER 3in1',
        sku: 1006009,
        category: 'category 2',
        sub_category: 'sub category 1',
        price: 16,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 5,
        code: 'PRME321',
        name: 'PREMIER 3in1 ECO ',
        sku: 1007000,
        category: 'category 2',
        sub_category: 'sub category 3',
        price: 15,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-29',
    },
    {
        id: 6,
        code: 'PRM21',
        name: 'PREMIER 2 1 Pkt',
        sku: 2007000,
        category: 'category 3',
        sub_category: 'sub category 1',
        price: 20,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-28',
    },
    {
        id: 1,
        code: 'BRB101',
        name: 'Bear Brand Swak Pack',
        sku: 1000001,
        category: 'category 1',
        sub_category: 'sub category 2',
        price: 15,
        uom: 'gram',
        qty: 20,
        date_added: '2018-07-30',
    },
    {
        id: 2,
        code: 'BRB102',
        name: 'Bear Brand Adult Plus',
        sku: 1000002,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 15,
        uom: 'gram',
        qty: 25,
        date_added: '2018-07-29',
    },
    {
        id: 3,
        code: 'MILO101',
        name: 'Milo',
        sku: 1000009,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 8,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 4,
        code: 'PRM301',
        name: 'PREMIER 3in1',
        sku: 1006009,
        category: 'category 2',
        sub_category: 'sub category 1',
        price: 16,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 5,
        code: 'PRME321',
        name: 'PREMIER 3in1 ECO ',
        sku: 1007000,
        category: 'category 2',
        sub_category: 'sub category 3',
        price: 15,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-29',
    },
    {
        id: 6,
        code: 'PRM21',
        name: 'PREMIER 2 1 Pkt',
        sku: 2007000,
        category: 'category 3',
        sub_category: 'sub category 1',
        price: 20,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-28',
    },
    {
        id: 1,
        code: 'BRB101',
        name: 'Bear Brand Swak Pack',
        sku: 1000001,
        category: 'category 1',
        sub_category: 'sub category 2',
        price: 15,
        uom: 'gram',
        qty: 20,
        date_added: '2018-07-30',
    },
    {
        id: 2,
        code: 'BRB102',
        name: 'Bear Brand Adult Plus',
        sku: 1000002,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 15,
        uom: 'gram',
        qty: 25,
        date_added: '2018-07-29',
    },
    {
        id: 3,
        code: 'MILO101',
        name: 'Milo',
        sku: 1000009,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 8,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 4,
        code: 'PRM301',
        name: 'PREMIER 3in1',
        sku: 1006009,
        category: 'category 2',
        sub_category: 'sub category 1',
        price: 16,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 5,
        code: 'PRME321',
        name: 'PREMIER 3in1 ECO ',
        sku: 1007000,
        category: 'category 2',
        sub_category: 'sub category 3',
        price: 15,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-29',
    },
    {
        id: 6,
        code: 'PRM21',
        name: 'PREMIER 2 1 Pkt',
        sku: 2007000,
        category: 'category 3',
        sub_category: 'sub category 1',
        price: 20,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-28',
    },
    {
        id: 1,
        code: 'BRB101',
        name: 'Bear Brand Swak Pack',
        sku: 1000001,
        category: 'category 1',
        sub_category: 'sub category 2',
        price: 15,
        uom: 'gram',
        qty: 20,
        date_added: '2018-07-30',
    },
    {
        id: 2,
        code: 'BRB102',
        name: 'Bear Brand Adult Plus',
        sku: 1000002,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 15,
        uom: 'gram',
        qty: 25,
        date_added: '2018-07-29',
    },
    {
        id: 3,
        code: 'MILO101',
        name: 'Milo',
        sku: 1000009,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 8,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 4,
        code: 'PRM301',
        name: 'PREMIER 3in1',
        sku: 1006009,
        category: 'category 2',
        sub_category: 'sub category 1',
        price: 16,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 5,
        code: 'PRME321',
        name: 'PREMIER 3in1 ECO ',
        sku: 1007000,
        category: 'category 2',
        sub_category: 'sub category 3',
        price: 15,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-29',
    },
    {
        id: 6,
        code: 'PRM21',
        name: 'PREMIER 2 1 Pkt',
        sku: 2007000,
        category: 'category 3',
        sub_category: 'sub category 1',
        price: 20,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-28',
    },
    {
        id: 1,
        code: 'BRB101',
        name: 'Bear Brand Swak Pack',
        sku: 1000001,
        category: 'category 1',
        sub_category: 'sub category 2',
        price: 15,
        uom: 'gram',
        qty: 20,
        date_added: '2018-07-30',
    },
    {
        id: 2,
        code: 'BRB102',
        name: 'Bear Brand Adult Plus',
        sku: 1000002,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 15,
        uom: 'gram',
        qty: 25,
        date_added: '2018-07-29',
    },
    {
        id: 3,
        code: 'MILO101',
        name: 'Milo',
        sku: 1000009,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 8,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 4,
        code: 'PRM301',
        name: 'PREMIER 3in1',
        sku: 1006009,
        category: 'category 2',
        sub_category: 'sub category 1',
        price: 16,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 5,
        code: 'PRME321',
        name: 'PREMIER 3in1 ECO ',
        sku: 1007000,
        category: 'category 2',
        sub_category: 'sub category 3',
        price: 15,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-29',
    },
    {
        id: 6,
        code: 'PRM21',
        name: 'PREMIER 2 1 Pkt',
        sku: 2007000,
        category: 'category 3',
        sub_category: 'sub category 1',
        price: 20,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-28',
    },
    {
        id: 1,
        code: 'BRB101',
        name: 'Bear Brand Swak Pack',
        sku: 1000001,
        category: 'category 1',
        sub_category: 'sub category 2',
        price: 15,
        uom: 'gram',
        qty: 20,
        date_added: '2018-07-30',
    },
    {
        id: 2,
        code: 'BRB102',
        name: 'Bear Brand Adult Plus',
        sku: 1000002,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 15,
        uom: 'gram',
        qty: 25,
        date_added: '2018-07-29',
    },
    {
        id: 3,
        code: 'MILO101',
        name: 'Milo',
        sku: 1000009,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 8,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 4,
        code: 'PRM301',
        name: 'PREMIER 3in1',
        sku: 1006009,
        category: 'category 2',
        sub_category: 'sub category 1',
        price: 16,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 5,
        code: 'PRME321',
        name: 'PREMIER 3in1 ECO ',
        sku: 1007000,
        category: 'category 2',
        sub_category: 'sub category 3',
        price: 15,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-29',
    },
    {
        id: 6,
        code: 'PRM21',
        name: 'PREMIER 2 1 Pkt',
        sku: 2007000,
        category: 'category 3',
        sub_category: 'sub category 1',
        price: 20,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-28',
    },
    {
        id: 1,
        code: 'BRB101',
        name: 'Bear Brand Swak Pack',
        sku: 1000001,
        category: 'category 1',
        sub_category: 'sub category 2',
        price: 15,
        uom: 'gram',
        qty: 20,
        date_added: '2018-07-30',
    },
    {
        id: 2,
        code: 'BRB102',
        name: 'Bear Brand Adult Plus',
        sku: 1000002,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 15,
        uom: 'gram',
        qty: 25,
        date_added: '2018-07-29',
    },
    {
        id: 3,
        code: 'MILO101',
        name: 'Milo',
        sku: 1000009,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 8,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 4,
        code: 'PRM301',
        name: 'PREMIER 3in1',
        sku: 1006009,
        category: 'category 2',
        sub_category: 'sub category 1',
        price: 16,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 5,
        code: 'PRME321',
        name: 'PREMIER 3in1 ECO ',
        sku: 1007000,
        category: 'category 2',
        sub_category: 'sub category 3',
        price: 15,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-29',
    },
    {
        id: 6,
        code: 'PRM21',
        name: 'PREMIER 2 1 Pkt',
        sku: 2007000,
        category: 'category 3',
        sub_category: 'sub category 1',
        price: 20,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-28',
    },
    {
        id: 1,
        code: 'BRB101',
        name: 'Bear Brand Swak Pack',
        sku: 1000001,
        category: 'category 1',
        sub_category: 'sub category 2',
        price: 15,
        uom: 'gram',
        qty: 20,
        date_added: '2018-07-30',
    },
    {
        id: 2,
        code: 'BRB102',
        name: 'Bear Brand Adult Plus',
        sku: 1000002,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 15,
        uom: 'gram',
        qty: 25,
        date_added: '2018-07-29',
    },
    {
        id: 3,
        code: 'MILO101',
        name: 'Milo',
        sku: 1000009,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 8,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 4,
        code: 'PRM301',
        name: 'PREMIER 3in1',
        sku: 1006009,
        category: 'category 2',
        sub_category: 'sub category 1',
        price: 16,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 5,
        code: 'PRME321',
        name: 'PREMIER 3in1 ECO ',
        sku: 1007000,
        category: 'category 2',
        sub_category: 'sub category 3',
        price: 15,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-29',
    },
    {
        id: 6,
        code: 'PRM21',
        name: 'PREMIER 2 1 Pkt',
        sku: 2007000,
        category: 'category 3',
        sub_category: 'sub category 1',
        price: 20,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-28',
    },
    {
        id: 1,
        code: 'BRB101',
        name: 'Bear Brand Swak Pack',
        sku: 1000001,
        category: 'category 1',
        sub_category: 'sub category 2',
        price: 15,
        uom: 'gram',
        qty: 20,
        date_added: '2018-07-30',
    },
    {
        id: 2,
        code: 'BRB102',
        name: 'Bear Brand Adult Plus',
        sku: 1000002,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 15,
        uom: 'gram',
        qty: 25,
        date_added: '2018-07-29',
    },
    {
        id: 3,
        code: 'MILO101',
        name: 'Milo',
        sku: 1000009,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 8,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 4,
        code: 'PRM301',
        name: 'PREMIER 3in1',
        sku: 1006009,
        category: 'category 2',
        sub_category: 'sub category 1',
        price: 16,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 5,
        code: 'PRME321',
        name: 'PREMIER 3in1 ECO ',
        sku: 1007000,
        category: 'category 2',
        sub_category: 'sub category 3',
        price: 15,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-29',
    },
    {
        id: 6,
        code: 'PRM21',
        name: 'PREMIER 2 1 Pkt',
        sku: 2007000,
        category: 'category 3',
        sub_category: 'sub category 1',
        price: 20,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-28',
    },
    {
        id: 1,
        code: 'BRB101',
        name: 'Bear Brand Swak Pack',
        sku: 1000001,
        category: 'category 1',
        sub_category: 'sub category 2',
        price: 15,
        uom: 'gram',
        qty: 20,
        date_added: '2018-07-30',
    },
    {
        id: 2,
        code: 'BRB102',
        name: 'Bear Brand Adult Plus',
        sku: 1000002,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 15,
        uom: 'gram',
        qty: 25,
        date_added: '2018-07-29',
    },
    {
        id: 3,
        code: 'MILO101',
        name: 'Milo',
        sku: 1000009,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 8,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 4,
        code: 'PRM301',
        name: 'PREMIER 3in1',
        sku: 1006009,
        category: 'category 2',
        sub_category: 'sub category 1',
        price: 16,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 5,
        code: 'PRME321',
        name: 'PREMIER 3in1 ECO ',
        sku: 1007000,
        category: 'category 2',
        sub_category: 'sub category 3',
        price: 15,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-29',
    },
    {
        id: 6,
        code: 'PRM21',
        name: 'PREMIER 2 1 Pkt',
        sku: 2007000,
        category: 'category 3',
        sub_category: 'sub category 1',
        price: 20,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-28',
    },
    {
        id: 1,
        code: 'BRB101',
        name: 'Bear Brand Swak Pack',
        sku: 1000001,
        category: 'category 1',
        sub_category: 'sub category 2',
        price: 15,
        uom: 'gram',
        qty: 20,
        date_added: '2018-07-30',
    },
    {
        id: 2,
        code: 'BRB102',
        name: 'Bear Brand Adult Plus',
        sku: 1000002,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 15,
        uom: 'gram',
        qty: 25,
        date_added: '2018-07-29',
    },
    {
        id: 3,
        code: 'MILO101',
        name: 'Milo',
        sku: 1000009,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 8,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 4,
        code: 'PRM301',
        name: 'PREMIER 3in1',
        sku: 1006009,
        category: 'category 2',
        sub_category: 'sub category 1',
        price: 16,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 5,
        code: 'PRME321',
        name: 'PREMIER 3in1 ECO ',
        sku: 1007000,
        category: 'category 2',
        sub_category: 'sub category 3',
        price: 15,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-29',
    },
    {
        id: 6,
        code: 'PRM21',
        name: 'PREMIER 2 1 Pkt',
        sku: 2007000,
        category: 'category 3',
        sub_category: 'sub category 1',
        price: 20,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-28',
    },
    {
        id: 1,
        code: 'BRB101',
        name: 'Bear Brand Swak Pack',
        sku: 1000001,
        category: 'category 1',
        sub_category: 'sub category 2',
        price: 15,
        uom: 'gram',
        qty: 20,
        date_added: '2018-07-30',
    },
    {
        id: 2,
        code: 'BRB102',
        name: 'Bear Brand Adult Plus',
        sku: 1000002,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 15,
        uom: 'gram',
        qty: 25,
        date_added: '2018-07-29',
    },
    {
        id: 3,
        code: 'MILO101',
        name: 'Milo',
        sku: 1000009,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 8,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 4,
        code: 'PRM301',
        name: 'PREMIER 3in1',
        sku: 1006009,
        category: 'category 2',
        sub_category: 'sub category 1',
        price: 16,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 5,
        code: 'PRME321',
        name: 'PREMIER 3in1 ECO ',
        sku: 1007000,
        category: 'category 2',
        sub_category: 'sub category 3',
        price: 15,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-29',
    },
    {
        id: 6,
        code: 'PRM21',
        name: 'PREMIER 2 1 Pkt',
        sku: 2007000,
        category: 'category 3',
        sub_category: 'sub category 1',
        price: 20,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-28',
    },
    {
        id: 1,
        code: 'BRB101',
        name: 'Bear Brand Swak Pack',
        sku: 1000001,
        category: 'category 1',
        sub_category: 'sub category 2',
        price: 15,
        uom: 'gram',
        qty: 20,
        date_added: '2018-07-30',
    },
    {
        id: 2,
        code: 'BRB102',
        name: 'Bear Brand Adult Plus',
        sku: 1000002,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 15,
        uom: 'gram',
        qty: 25,
        date_added: '2018-07-29',
    },
    {
        id: 3,
        code: 'MILO101',
        name: 'Milo',
        sku: 1000009,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 8,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 4,
        code: 'PRM301',
        name: 'PREMIER 3in1',
        sku: 1006009,
        category: 'category 2',
        sub_category: 'sub category 1',
        price: 16,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 5,
        code: 'PRME321',
        name: 'PREMIER 3in1 ECO ',
        sku: 1007000,
        category: 'category 2',
        sub_category: 'sub category 3',
        price: 15,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-29',
    },
    {
        id: 6,
        code: 'PRM21',
        name: 'PREMIER 2 1 Pkt',
        sku: 2007000,
        category: 'category 3',
        sub_category: 'sub category 1',
        price: 20,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-28',
    },
    {
        id: 1,
        code: 'BRB101',
        name: 'Bear Brand Swak Pack',
        sku: 1000001,
        category: 'category 1',
        sub_category: 'sub category 2',
        price: 15,
        uom: 'gram',
        qty: 20,
        date_added: '2018-07-30',
    },
    {
        id: 2,
        code: 'BRB102',
        name: 'Bear Brand Adult Plus',
        sku: 1000002,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 15,
        uom: 'gram',
        qty: 25,
        date_added: '2018-07-29',
    },
    {
        id: 3,
        code: 'MILO101',
        name: 'Milo',
        sku: 1000009,
        category: 'category 1',
        sub_category: 'sub category 1',
        price: 8,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 4,
        code: 'PRM301',
        name: 'PREMIER 3in1',
        sku: 1006009,
        category: 'category 2',
        sub_category: 'sub category 1',
        price: 16,
        uom: 'gram',
        qty: 50,
        date_added: '2018-07-29',
    },
    {
        id: 5,
        code: 'PRME321',
        name: 'PREMIER 3in1 ECO ',
        sku: 1007000,
        category: 'category 2',
        sub_category: 'sub category 3',
        price: 15,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-29',
    },
    {
        id: 6,
        code: 'PRM21',
        name: 'PREMIER 2 1 Pkt',
        sku: 2007000,
        category: 'category 3',
        sub_category: 'sub category 1',
        price: 20,
        uom: 'gram',
        qty: 100,
        date_added: '2018-07-28',
    },
]
