import { InventoryReturns } from "./inventory.model";

export const testInventoryReturnedList: InventoryReturns[] = [
    {
        productname: 'Bear Brand Swak Pack',
        qty: 20,
        retailer: 'Retailer1',
        return_type: 'Damaged',
        agent: 'Arceo',
        status: 'Not Received',
        date_returned: '2018-07-30',
    },
    {
        productname: 'Milo',
        qty: 10,
        retailer: 'Retailer2',
        return_type: 'Damaged',
        agent: 'Arceo',
        status: 'Not Received',
        date_returned: '2018-07-30',
    },
    {
        productname: 'Bear Brand Swak Pack',
        qty: 20,
        retailer: 'Retailer1',
        return_type: 'Expired',
        agent: 'Marlou',
        status: 'Not Received',
        date_returned: '2018-07-30',
    },
    {
        productname: 'Bear Brand',
        qty: 20,
        retailer: 'Retailer1',
        return_type: 'Damaged',
        agent: 'Arceo',
        status: 'Not Received',
        date_returned: '2018-07-30',
    },
    {
        productname: 'Bears Brand Swak Pack',
        qty: 20,
        retailer: 'Retailer1',
        return_type: 'Damaged',
        agent: 'Arceo',
        status: 'Received',
        date_returned: '2018-07-30',
    },
    {
        productname: 'Bears Brand Swak Pack',
        qty: 20,
        retailer: 'Retailer1',
        return_type: 'Damaged',
        agent: 'Arceo',
        status: 'Received',
        date_returned: '2018-07-30',
    },
    {
        productname: 'Bears Brand Swak Pack',
        qty: 20,
        retailer: 'Retailer1',
        return_type: 'Damaged',
        agent: 'Arceo',
        status: 'Received',
        date_returned: '2018-07-30',
    },
    {
        productname: 'Bears Brand Swak Pack',
        qty: 20,
        retailer: 'Retailer1',
        return_type: 'Damaged',
        agent: 'Arceo',
        status: 'Received',
        date_returned: '2018-09-04',
    },
]
